### ISSUE TITLE
board name incorrect in boards.txt file

### ISSUE THREAD

**Issue by deepcoder** [rayshobby/ESPToy#1]
The line in the boards.txt file:

esptoy.name=OpenSprinklerHW2.2 (16MHz, Serial)

seems to have the wrong name for the board, according to this blog post:

http://rayshobby.net/?p=10156

the board name should be 'ESPToy'

'Next, launch the Arduino IDE, select Tools->Board->ESPToy,'

**Comment by rayshobby** [comment]
You are right, the board name should be ESPToy. I just updated it. Thanks
